from .research_tools import (
    read_file,
    write_file,
    list_files,
    report_findings,
    get_findings,
    score_risk,
    record_plan,
    get_plan,
    record_threat_model,
    get_threat_model,
    record_summary,
    get_summary,
    record_exploit_chain,
    record_learning,
    dedupe_findings,
    generate_report,
    calibrate_finding,
    get_security_guidance,
    query_lineage,
)
from .sandbox_tools import run_sandbox, apply_patch

TOOLS: dict[str, object] = {
    "read_file": read_file,
    "write_file": write_file,
    "list_files": list_files,
    "report_findings": report_findings,
    "get_findings": get_findings,
    "score_risk": score_risk,
    "calibrate_finding": calibrate_finding,
    "record_plan": record_plan,
    "get_plan": get_plan,
    "record_threat_model": record_threat_model,
    "get_threat_model": get_threat_model,
    "record_summary": record_summary,
    "get_summary": get_summary,
    "record_exploit_chain": record_exploit_chain,
    "record_learning": record_learning,
    "dedupe_findings": dedupe_findings,
    "generate_report": generate_report,
    "run_sandbox": run_sandbox,
    "apply_patch": apply_patch,
    "get_security_guidance": get_security_guidance,
    "query_lineage": query_lineage,
}
